version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: excoveralls
    versions:
    - 0.13.4
  - dependency-name: sentry
    versions:
    - 8.0.4
  - dependency-name: tesla
    versions:
    - 1.4.0
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
